---
  - name: "Enabling Zabbix Repo"
    apt:
      deb: "https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1+debian10_all.deb"
  - name: "Installing Zabbix Agent"
    apt:
      name: "zabbix-agent"
      state: latest
      update_cache: yes
    register: results

  - name: "Implementing Zabbix Agent Config"
    copy:
      src: '{{ role_path }}/files/zabbix_agentd.conf'
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: '0644'

  - name: "Starting and Enabling Zabbix Agent"
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      masked: no
      name: zabbix-agent
