---
  - name: "Installing Zabbix Repo"
    yum:
      name: "https://repo.zabbix.com/zabbix/5.2/rhel/7/x86_64/zabbix-release-5.2-1.el7.noarch.rpm"
      state: present
      update_cache: yes

  - name: "Installing Zabbix Agent"
    yum:
      name: "zabbix-agent"
      state: latest

  - name: "Implementing Zabbix Agent Config"
    copy:
      src: '{{ role_path }}/files/zabbix_agentd.conf'
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: '0644'

  - name: "Enabling and Starting Zabbix"
    systemd:
      state: restarted
      daemon_reload: yes
      enabled: yes
      masked: no
      name: zabbix-agent
